language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - nightly
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
sudo: false
# Python 3.7 isn't available on trusty, so needs a separate build config
cache:
  - pip
services:
  - redis-server
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install -r requirements-26.txt; fi
  - pip install -r requirements.txt
  - pip install coverage python-coveralls
before_script:
  - flake8
script:
  - coverage erase
  - coverage run --source fakeredis test_fakeredis.py
notifications:
  email:
    - js@jamesls.com
    - bmerry@ska.ac.za
after_success: coveralls
