language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
services:
  - redis-server
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install -r requirements-26.txt; fi
  - pip install -r requirements.txt
  - pip install coverage python-coveralls
script:
  - coverage erase
  - coverage run --source fakeredis.py test_fakeredis.py
notifications:
  email:
    - js@jamesls.com
after_success: coveralls
